[feature #156577846] Create departments and add checks to departments
andela/hc-rogue-one pull request #22
Opened 2018-05-17 10:58 UTC by hariclerry

#### What does this PR do?
Ensure that Teams can view all jobs in the team account dashboard listed together as one view

#### Description of Tasks to be complete
Create different departments, add checks to departments and filter departments so that when teams log in to the dashboard they should be able to view the jobs per department.

#### How should this be manually tested?
1: Install the project and install the requirements.txt
2: Start the server by running; python manage.py runserver, open localhost  http://localhost:8080 in the browser
3: Login into the site
4: Click the dropdown menu showing the user email address and click Departments link
5: On the department page create department and save it
6: Go to the create checks links, add the check name and department
7: Click on the Department dropdown menu and select department
4: You should be able to view checks for that particular department.
#### What are the relevant pivotal tracker stories?
#156577846
#### Checklist: I completed these to help reviewers
- [x] My IDE is configured to follow the PEP8 Conventions

No? Unsure? -> configure your IDE, format the code and add the changes with git add . && git commit --amend
- [x] I have added tests to cover my changes. (If you refactored
existing code that was well tested you do not have to add tests)

No? -> write tests and add them to this commit git add . && git commit --amend

- [x] All new and existing tests passed.

No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is based on the latest changes of the develop branch.

No? Unsure? -> execute command git pull --rebase origin develop

2018-05-17 11:00 UTC, hariclerry commented
Hello Team, please review my code and let me know what you guys think.

2018-05-17 14:35 UTC, dondrzzy requested changes
I have run your branch and it looks good. Nice work. These are my UX and UI reviews
1: It would be better to place the departments link on the dashboard as opposed to the drop downlink that usually holds links to logout and account_settings
2:The filter on the failed checks view does not work
3: The placement of the edit department is also off. Its under name. The <th>name</th> should contain a name. It might be better to add it the department to the table columns(td).
4: The departments filter on the checks page would in my view look better if you float it to the right. Or just to the right of the `failed_checks` button and and of the same size maybe to provide more sync. In my view.

2018-05-17 16:43 UTC, hariclerry commented
@dondrzzy, great that you pointed those things out, I will work on them. But for the placement of the edit department button, am following health checks UI design.

2018-05-17 16:57 UTC, hariclerry commented
And also, the failed checks filter is working on my machine.

2018-05-18 09:07 UTC, dondrzzy requested changes
I have run your branch and it looks good. Nice work. These are my UX and UI reviews
1: It would be better to place the departments link on the dashboard as opposed to the drop downlink that usually holds links to logout and account_settings
2:The filter on the failed checks view does not work
3: The placement of the edit department is also off. Its under name. The <th>name</th> should contain a name. It might be better to add it the department to the table columns(td).
4: The departments filter on the checks page would in my view look better if you float it to the right. Or just to the right of the `failed_checks` button and and of the same size maybe to provide more sync. In my view.

2018-05-18 10:17 UTC, Elbertbiggs360 commented on hc/front/tests/test_add_department.py
> +        self.client.get("/departments/add/")
unnecessary line here

2018-05-18 10:27 UTC, hariclerry commented on hc/front/tests/test_add_department.py
> +        self.client.get("/departments/add/")
Okay. Worked on that.

2018-05-18 11:36 UTC, merged